DEBUG|2021-03-15 17:30:17,168|LogManager(startElab:43)| backOffice.Loader: Elaboratione iniziata
DEBUG|2021-03-15 17:30:17,341|LogManager(EndElab:79)| backOffice.Loader: Elaboration in errore.Errore  durante l'inserimento massivo per la riga : - Messaggio d'errore: ERROR: relation "batch.tab_prova" does not exist
